spring:
  datasource:
    url: jdbc:h2:mem:ssm-demo;MODE=MYSQL
    username: root
    password: root
    driverClassName: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
#showSql
logging:
  level:
    com:
      example:
        mapper : debug

